# Generated by Django 4.0.8 on 2024-03-05 14:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
        ('observatories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sigthing',
            fields=[
                ('creation_datetime', models.DateTimeField(auto_now_add=True)),
                ('modification_datetime', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField()),
                ('device_matrix', models.TextField(max_length=512)),
                ('asteroid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asteroid_sightings', to='devices.device')),
                ('device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_sightings', to='devices.device')),
                ('observatory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observatory_sightings', to='observatories.observatory')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
