# Generated by Django 4.0.8 on 2024-03-05 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('observatories', '0002_alter_observatory_options'),
        ('devices', '0001_initial'),
        ('sightings', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sigthing',
            new_name='Sighting',
        ),
    ]
