# Generated by Django 4.0.8 on 2024-03-05 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('observatories', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='observatory',
            options={'verbose_name': 'Observatory', 'verbose_name_plural': 'Observatories'},
        ),
    ]
