# Generated by Django 4.0.8 on 2024-03-05 14:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('creation_datetime', models.DateTimeField(auto_now_add=True)),
                ('modification_datetime', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=128)),
                ('description', models.TextField(blank=True, max_length=512, null=True)),
                ('r_height', models.IntegerField()),
                ('r_weight', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
