# Generated by Django 4.0.8 on 2024-03-06 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='r_weight',
            new_name='r_width',
        ),
    ]
