# Generated by Django 4.0.8 on 2024-03-06 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asteroids', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asteroid',
            name='r_height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asteroid',
            name='r_width',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
